Fix warnings/test Admin
AgileVentures/kcsc_admin pull request #35
Opened 2021-09-07 15:39 UTC by 1CIM

### PT: https://www.pivotaltracker.com/story/show/179494566

### Changes: 
- fix various warnings in console
- fix failing tests
- Add a PT for general dashboard. too big fix for this pr i think

2021-09-07 16:04 UTC, SevaDer14 requested changes

2021-09-07 16:04 UTC, SevaDer14 commented on cypress/integration/adminCanEditNavigation.feature.js
> +          // })
comments

2021-09-07 16:04 UTC, SevaDer14 commented on cypress/integration/adminCanUseSectionsDashboard.feature.js
> +      it.only('is expected to create new card', () => {
.only

2021-09-08 06:19 UTC, 1CIM commented on cypress/integration/adminCanEditNavigation.feature.js
> +          // })
fixed

2021-09-08 06:19 UTC, 1CIM commented on cypress/integration/adminCanUseSectionsDashboard.feature.js
> +      it.only('is expected to create new card', () => {
fixed

2021-09-08 07:26 UTC, SevaDer14 approved these changes

2021-09-08 07:28 UTC, merged